"""Add description to parking exception

Revision ID: 0cc1ac110abf
Revises: 94d5e2719cab
Create Date: 2025-10-26 20:01:31.590948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cc1ac110abf"
down_revision: Union[str, Sequence[str], None] = "94d5e2719cab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parking_exception", sa.Column("description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parking_exception", "description")
    # ### end Alembic commands ###
