"""Add geolocation

Revision ID: 6e5cc093f2ba
Revises:
Create Date: 2025-09-27 23:28:01.657562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e5cc093f2ba"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("BR", name="country").create(op.get_bind())
    op.create_table(
        "state",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "country",
            postgresql.ENUM("BR", name="country", create_type=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("iso2_code", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__state")),
        sa.UniqueConstraint(
            "country", "iso2_code", name=op.f("uq__state__countryiso2_code")
        ),
        sa.UniqueConstraint("name", name=op.f("uq__state__name")),
    )
    op.create_table(
        "city",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identification_code", sa.String(), nullable=True),
        sa.Column(
            "country",
            postgresql.ENUM("BR", name="country", create_type=False),
            nullable=False,
        ),
        sa.Column("state_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["state_id"], ["state.id"], name=op.f("fk__city__state_id__state")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__city")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("city")
    op.drop_table("state")
    sa.Enum("BR", name="country").drop(op.get_bind())
    # ### end Alembic commands ###
