"""Add key field to company image

Revision ID: 94d5e2719cab
Revises: c236507349bc
Create Date: 2025-10-26 19:40:25.919254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94d5e2719cab"
down_revision: Union[str, Sequence[str], None] = "c236507349bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company_image", sa.Column("key", sa.String(), nullable=False))
    op.drop_column("company_image", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_image",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("company_image", "key")
    # ### end Alembic commands ###
