"""Add organization

Revision ID: 9658dfac3d1e
Revises: 07ed4d290c0c
Create Date: 2025-09-29 02:18:32.890133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9658dfac3d1e"
down_revision: Union[str, Sequence[str], None] = "07ed4d290c0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("register_code", sa.String(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["state_id"], ["state.id"], name=op.f("fk__organization__state_id__state")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__organization__user_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__organization")),
        sa.UniqueConstraint("user_id", name=op.f("uq__organization__user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization")
    # ### end Alembic commands ###
